### ISSUE TITLE
Unable to use cross-stack variable for state machine definition's QueueUrl parameter

### ISSUE THREAD

**Issue by jcortega** [horike37/serverless-step-functions#253]
# This is a Bug Report 

## Description
When using exported variable from another stack/service for queue url (ie Fn::ImportValue), plugin errors out with the message below.

```
Serverless: Packaging service...
Unable to parse SQS queue url [[object Object]]
Unable to parse SQS queue url [[object Object]]
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....
Serverless: Operation failed!
Serverless: 

  Serverless Error ---------------------------------------
  An error occurred: IamRoleStateMachineExecution - Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: cfeb18ea-d13a-11e9-802b-b9c99487764f).
```
Error occurs when the plugin tries to generate IAM policy statement given the QueueUrl parameter. However, since Fn::ImportValue requires fetching current state from Cloudformation, the URL is not readily available for the plugin to parse.

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.46.0
* ***The Plugin Version you're using***: 2.6.0
* ***Operating System***: amazon linux

## Step function definition
```stepFunctions:
  stateMachines:
    updateCMI:
      events:
        - http:
            path: updatecmi
            method: post
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: {"Fn::ImportValue": "authorizer-${file(../../config/provider.yml):stage}-id"}
      definition:
        StartAt: updateInfra
        States:
          updateInfra:
            Type: Task
            TimeoutSeconds: 300
            Parameters:
              QueueUrl: 
                'Fn::ImportValue': infradeployer-${self:custom.stage}-queue-url
              MessageAttributes:
                IntegrationID:
                  DataType: String
                  StringValue.$: $.integration_id
                OrganizationID:
                  DataType: String
                  StringValue.$: $.organization_id
                Action:
                  DataType: String
                  StringValue.$: $.action
                TaskToken:
                  DataType: String
                  StringValue.$: $$.Task.Token
              MessageBody: "{}"
            Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
            Next: choiceStateAction
            ResultPath: $.taskresult
            Retry:
            - ErrorEquals:
              - States.ALL
              IntervalSeconds: 3
              MaxAttempts: 2
              BackoffRate: 1.5
--snipped--
```

Also tried using ${cf:*} variable. Plugin (or serverless?) errors out with the message below.

```
Serverless: Packaging service...

  Type Error ---------------------------------------------

  Cannot read property 'startsWith' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by theburningmonk** [comment]
@jcortega can you include the state machine definition in here? at least enough of it for me to reproduce the issue?

**Comment by jcortega** [comment]
@theburningmonk i have updated the issue description with the state machine definition. thanks!

**Comment by stevecaldwell77** [comment]
I'm having the same problem trying to use `Fn::ImportValue` to specify a role:

```
stepFunctions:
  stateMachines:
    myStateMachine:
      definition: '${file(myStateMachine.yml)}'
      id: MyStateMachine
      name: 'my-state-machine'
      role:
        'Fn::ImportValue': IamRoleExportedByOtherStack
```

gives me:

```
State machine [myStateMachine] is malformed. Please check the README for more info. ValidationError: child "role" fails because ["role" must be a string, "Fn::ImportValue" is not allowed, "Fn::ImportValue" is not allowed]
```


It works in `v2.4.0`, the issue starts appearing with `2.5.0`

**Comment by FilipPyrek** [comment]
@jcortega we are experiencing the same issue. 👍 

The problem is here: https://github.com/horike37/serverless-step-functions/blob/4256648cc863bc195a8911ae0f9883defced328e/lib/deploy/stepFunctions/compileIamRole.js#L38-L44

**Comment by theburningmonk** [comment]
Thanks @FilipPyrek 👍

**Comment by FilipPyrek** [comment]
Solved with #261

**Comment by stevecaldwell77** [comment]
The issue I mentioned with trying to use `Fn::ImportValue` for the role is still not fixed. I'll open a separate issue.

**Comment by stevecaldwell77** [comment]
I created #262 for tracking the role issue.
